Update helm.yaml

diff --git a/.github/workflows/helm.yaml b/.github/workflows/helm.yaml
--- a/.github/workflows/helm.yaml
+++ b/.github/workflows/helm.yaml
@@ -6,57 +6,125 @@ on:
   workflow_dispatch:
   push:
     branches:
-      - main
+      - pre-deployment
     paths:
-      - 'temp/**'
+      - 'app/**'
 
 jobs:
-  release:
+  update-helm-chart:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
         with:
           path: 'src'
-          ref: 'main'
+          ref: ${{ github.sha }}
           fetch-depth: 0
 
-      - name: Checkout
-        uses: actions/checkout@v2
-        with:
-          path: 'dest'
-          ref: 'gh-pages'
-          fetch-depth: 0
-
-      - name: Install Helm
-        uses: azure/setup-helm@v1
-
-      - name: Update New Files and push to master branch
+      - name: Identify destiny branch name
+        id: dest-branch
         shell: bash
         working-directory: src
         run: |
-          helm repo index ./temp --merge ../dest/index.yaml --url https://raw.githubusercontent.com/john-afrano/helm-repository/gh-pages/helm/
-          mkdir -p ../dest/helm
-          echo "Copying files..."
-          shopt -s extglob
-          mkdir -p ./helm/
-          echo "n" | cp -pr ./temp/!(index.yaml) ../dest/helm/
-          echo "n" | cp -pr ./temp/!(index.yaml) ./helm/
-          echo "n" | cp -pr ./temp/index.yaml ../dest/
-          echo "y" | rm -rf ./temp/*
-          git config user.name "helm"
-          git config user.email "platform-engineer@example.com"
-          git add .
-          git commit -m "Updated from ref: $GITHUB_SHA"
-          git push
+            COMMIT_BRANCH=$(git log -n 1 --pretty=format:"%s" ${{ github.sha }})
 
-      - name: Push New Files
+            if [[ $COMMIT_BRANCH == main || $COMMIT_BRANCH == master ]]; then
+              DEST_BRANCH=production
+            elif [[ $COMMIT_BRANCH == hot* || $COMMIT_BRANCH == release* ]]; then
+              DEST_BRANCH=stage
+            elif [[ $COMMIT_BRANCH == dev* || $COMMIT_BRANCH == feat* || $COMMIT_BRANCH == fix* ]]; then
+              DEST_BRANCH=develop
+            else
+              DEST_BRANCH=develop
+            fi
+
+            echo "DEST_BRANCH=${DEST_BRANCH}" >> $GITHUB_OUTPUT
+
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          path: 'dest'
+          ref: '${{ steps.dest-branch.outputs.DEST_BRANCH }}'
+          fetch-depth: 0
+
+      - name: Set up Helm
+        uses: azure/setup-helm@v3
+        with:
+          version: 'v3.11.1'
+
+      - name: Update New Files and push to dest branch
+        shell: bash
+        working-directory: src
+        run: |
+            set -e
+
+            shopt -s extglob
+
+            file_list=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} -- ./app)
+            
+            mkdir -p aux_dir
+            
+            for file in $file_list; do
+              echo "file: ${file}"
+              if [ -f "$file" ]; then
+                  mv "$file" ./aux_dir
+              else
+                  echo "Error: File '$file' does not exist."
+              fi
+            done
+
+            url=$(echo "https://raw.githubusercontent.com/john-afrano/helm-repository/${{ steps.dest-branch.outputs.DEST_BRANCH }}/helm/")
+            
+            if [ -n "$(find ./aux_dir -type f -name '*.tgz')" ]; then
+              if ! helm repo index ./aux_dir --merge ../dest/index.yaml --url $url; then
+                echo "Error: Failed to generate repository index."
+                exit 1
+              fi
+              
+              
+              mkdir -p ../dest/helm
+              
+              echo "Copying files..."              
+
+              if ! cp -pr ./aux_dir/!(index.yaml) ../dest/helm/; then
+                  echo "Error: Failed to copy files to the destination directory."
+                  exit 1
+              fi
+
+              if ! cp -pr ./aux_dir/index.yaml ../dest/; then
+                  echo "Error: Failed to copy the index file to the destination directory."
+                  exit 1
+              fi
+            else
+              echo "Warning: No .tgz files found in ./aux_dir. Skipping index generation."
+            fi
+
+      - name: Commit alterations to dest branch and push files
         shell: bash
         working-directory: dest
         run: |
-          git config user.name "helm"
-          git config user.email "platform-engineer@example.com"
-          git add $(git ls-files -o --exclude-standard)
-          git add index.yaml
-          git commit -m "Updated from ref: $GITHUB_SHA"
-          git push
+          git config user.name "$GITHUB_ACTOR"
+          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
+
+          if [[ $(git status --porcelain) ]]; then
+            
+            if ! git add .; then
+              echo "Error: Failed to stage the changes for commit."
+              exit 1
+            fi
+            
+            if ! git commit -m "Updated from ref: ${{ github.sha }}"; then
+              echo "Error: Failed to commit the changes."
+              exit 1
+            fi
+            
+            if ! git push; then
+              echo "Error: Failed to push the changes to the remote repository."
+              if ! git pull --rebase && git push; then
+                echo "Error: Failed to merge and push the changes."
+                exit 1
+              fi
+            fi
+          else
+            echo "No changes to commit."
+          fi
